services:
  - type: web
    name: uk-companies-house-scraper
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: BROWSERBASE_API_KEY
        sync: false
      - key: BROWSERBASE_PROJECT_ID
        sync: false
